apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  template:
    spec:
      containers:
      - name: spark
        image: bitnami/spark:3.4.1
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          spark-submit --master local /opt/spark-apps/app.py
        volumeMounts:
        - name: spark-app
          mountPath: /opt/spark-apps
      restartPolicy: Never
      volumes:
      - name: spark-app
        configMap:
          name: spark-app-cm
