apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      containers:
      - name: spark
        image: bitnami/spark:3.4.1
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          export HOME=/tmp && \
          mkdir -p $HOME/.ivy2 && \
          spark-submit \
            --conf spark.jars.ivy=/tmp/.ivy2 \
            --conf spark.jars.repositories= \
            --conf spark.jars.packages='' \
            --master local \
            /opt/spark-apps/app.py
        volumeMounts:
        - name: spark-app
          mountPath: /opt/spark-apps
      restartPolicy: Never
      volumes:
      - name: spark-app
        configMap:
          name: spark-app-cm
